// Vite needs us to tell it which packages are which, see: https://vitejs.dev/guide/ssr.html#ssr-externals
// Hopefully this isn’t needed over time, but for now there are errors in automatic detection.
// Neither list has to be comprehensive; simply add packages as errors arise (they will be obvious)
export const ESM_EXTERNALS = new Set([
  '@astrojs/markdown-support',
  '@astrojs/parser',
  '@astrojs/renderer-preact',
  '@astrojs/renderer-react',
  '@astrojs/renderer-svelte',
  '@astrojs/renderer-vue',
  'astro',
  'preact',
  'slash',
  'string-width',
  'svelte',
]);
export const CJS_EXTERNALS = new Set([
  '@babel/code-frame',
  '@babel/generator',
  '@babel/parser',
  '@babel/traverse',
  'autoprefixer',
  'astring',
  'emoji-regex',
  'esbuild',
  'estree',
  'estree-util-value-to-estree',
  'github-slugger',
  'gray-matter',
  'find-up',
  'mime',
  'min-indent',
  'postcss',
  'postcss-icss-keyframes',
  'react',
  'react-dom',
  'rehype-expressions',
  'rehype-raw',
  'rehype-stringify',
  'remark',
  'remark-footnotes',
  'remark-gfm',
  'remark-parse',
  'remark-rehype',
  'sass',
  'shorthash',
  'unified',
  'vue',
]);
